In [19]:
import torch
torch.manual_seed(1998)

a = torch.randn(1,2,5)
print("a:", a)
b = torch.randn(1,2,5)
print("b:", b)
c = torch.randn(1,2,5)
print("c:", c)

d = torch.cat((a,b,c))
print("d:", d)

a: tensor([[[-0.0425, -1.2378,  0.3265, -0.9915,  1.3749],
         [-0.3638, -0.2614, -0.2109,  0.5516,  0.9428]]])
b: tensor([[[ 1.0430, -0.4688, -0.7154,  1.2267,  0.6224],
         [-1.8406, -1.3268,  0.8080,  1.6059, -0.0416]]])
c: tensor([[[ 1.4931,  0.1347, -1.1590,  2.6858,  1.7739],
         [ 0.6319,  0.6445, -0.3881,  1.7773,  0.5696]]])
d: tensor([[[-0.0425, -1.2378,  0.3265, -0.9915,  1.3749],
         [-0.3638, -0.2614, -0.2109,  0.5516,  0.9428]],

        [[ 1.0430, -0.4688, -0.7154,  1.2267,  0.6224],
         [-1.8406, -1.3268,  0.8080,  1.6059, -0.0416]],

        [[ 1.4931,  0.1347, -1.1590,  2.6858,  1.7739],
         [ 0.6319,  0.6445, -0.3881,  1.7773,  0.5696]]])


In [20]:
import torch

# set the seed for reproducibility
torch.manual_seed(1998)

# create three tensors
a = torch.randn(1, 2, 5)
b = torch.randn(1, 2, 5)
c = torch.randn(1, 2, 5)

# concatenate the tensors in a loop
d = None
for tensor in [a, b, c]:
    if d is None:
        d = tensor
    else:
        d = torch.cat((d, tensor), dim=0)

print("d:", d)
print("d shape:", d.shape)


d: tensor([[[-0.0425, -1.2378,  0.3265, -0.9915,  1.3749],
         [-0.3638, -0.2614, -0.2109,  0.5516,  0.9428]],

        [[ 1.0430, -0.4688, -0.7154,  1.2267,  0.6224],
         [-1.8406, -1.3268,  0.8080,  1.6059, -0.0416]],

        [[ 1.4931,  0.1347, -1.1590,  2.6858,  1.7739],
         [ 0.6319,  0.6445, -0.3881,  1.7773,  0.5696]]])
d shape: torch.Size([3, 2, 5])


In [22]:
import torch

# set the seed for reproducibility
torch.manual_seed(1998)
num = 10
d = None
for i in range (num):
    a = torch.randn(1,2,5)
    if d == None:
        d = a
    else:
        d = torch.cat((d,a),dim = 0)

print(d)
print(d.shape)
        

tensor([[[-0.0425, -1.2378,  0.3265, -0.9915,  1.3749],
         [-0.3638, -0.2614, -0.2109,  0.5516,  0.9428]],

        [[ 1.0430, -0.4688, -0.7154,  1.2267,  0.6224],
         [-1.8406, -1.3268,  0.8080,  1.6059, -0.0416]],

        [[ 1.4931,  0.1347, -1.1590,  2.6858,  1.7739],
         [ 0.6319,  0.6445, -0.3881,  1.7773,  0.5696]],

        [[-2.6679,  0.5392, -0.7834, -0.1990,  0.5612],
         [-1.2274,  0.0555, -1.0306, -0.7704, -0.0169]],

        [[-0.0129, -0.3114, -1.5811, -1.8386,  0.0603],
         [-1.3166, -0.3594,  1.3553, -0.0824,  0.1377]],

        [[-1.2240,  1.5110,  0.1946, -1.6055,  1.3390],
         [ 1.4399,  1.8787,  0.4816, -0.0916,  1.1109]],

        [[-0.0713, -0.6167,  1.2817,  1.5684,  0.2291],
         [-1.5450, -0.4998,  1.5983, -1.3581, -0.4392]],

        [[-1.2058, -1.2961,  0.1553,  1.2397,  0.6901],
         [ 0.8224,  0.8444,  0.1052,  0.2202, -0.8280]],

        [[ 0.1093,  0.9359,  0.5486, -0.7403, -1.5950],
         [-0.5269, -0.6531,  0.3

In [23]:
import torch

# set the seed for reproducibility
torch.manual_seed(1998)
num = 10
d = torch.empty(num,2,5)
for i in range (num):
    a = torch.randn(1,2,5)
    d[i] = a

print(d)
print(d.shape)
        

tensor([[[-0.0425, -1.2378,  0.3265, -0.9915,  1.3749],
         [-0.3638, -0.2614, -0.2109,  0.5516,  0.9428]],

        [[ 1.0430, -0.4688, -0.7154,  1.2267,  0.6224],
         [-1.8406, -1.3268,  0.8080,  1.6059, -0.0416]],

        [[ 1.4931,  0.1347, -1.1590,  2.6858,  1.7739],
         [ 0.6319,  0.6445, -0.3881,  1.7773,  0.5696]],

        [[-2.6679,  0.5392, -0.7834, -0.1990,  0.5612],
         [-1.2274,  0.0555, -1.0306, -0.7704, -0.0169]],

        [[-0.0129, -0.3114, -1.5811, -1.8386,  0.0603],
         [-1.3166, -0.3594,  1.3553, -0.0824,  0.1377]],

        [[-1.2240,  1.5110,  0.1946, -1.6055,  1.3390],
         [ 1.4399,  1.8787,  0.4816, -0.0916,  1.1109]],

        [[-0.0713, -0.6167,  1.2817,  1.5684,  0.2291],
         [-1.5450, -0.4998,  1.5983, -1.3581, -0.4392]],

        [[-1.2058, -1.2961,  0.1553,  1.2397,  0.6901],
         [ 0.8224,  0.8444,  0.1052,  0.2202, -0.8280]],

        [[ 0.1093,  0.9359,  0.5486, -0.7403, -1.5950],
         [-0.5269, -0.6531,  0.3

In [24]:
import numpy as np

arr = np.array([0, 3, 7, 10])
opposite_diff = np.cumsum(arr)

print(opposite_diff)  # Output: [0 3 10 20]


[ 0  3 10 20]


In [30]:
import numpy as np

a = {11: 2803, 12: 871, 21: 911, 22: 797, 31: 515, 32: 1637}
b = np.cumsum([a[key] for key in a.keys()])
print("b:", b)

b: [2803 3674 4585 5382 5897 7534]


In [35]:
import numpy as np

a = np.random.randn(1,10)
print("a:", a)
print(1.0(a))

a: [[ 0.59950201 -0.66277892  0.9696664   1.6049337   1.05578184 -1.36338263
   0.85234066 -0.63471524 -0.9423559   0.1100589 ]]


<>:5: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<>:5: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
/var/folders/rr/kr1f9bzj1p75mdz4_tr4hc480000gn/T/ipykernel_4522/3903341760.py:5: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
  print(1.0(a))
/var/folders/rr/kr1f9bzj1p75mdz4_tr4hc480000gn/T/ipykernel_4522/3903341760.py:5: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
  print(1.0(a))
/var/folders/rr/kr1f9bzj1p75mdz4_tr4hc480000gn/T/ipykernel_4522/3903341760.py:5: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
  print(1.0(a))
/var/folders/rr/kr1f9bzj1p75mdz4_tr4hc480000gn/T/ipykernel_4522/3903341760.py:5: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
  print(1.0(a))


TypeError: 'float' object is not callable